#!/usr/bin/env bash

# List ECR images with tags in a given registry and repository.

region=us-east-1

aws ecr describe-images \
  --registry "$1" --repository-name "$2" --region "$region" --page-size 999 \
  | jq --arg region "$region" -r '
    .imageDetails | map(select(.imageTags != null)) | sort_by(.imagePushedAt)[]
    | @text "\(.imagePushedAt|todate)  \(.registryId).dkr.ecr.\($region).amazonaws.com/\(.repositoryName)@\(.imageDigest)  \(.imageTags|join(","))"
  '
