#!/usr/bin/env bash

# Browse and open selection of Chrome history.
# Taken from: https://github.com/junegunn/fzf/wiki/examples#browsing-history

cols=$(( $(tput cols) / 3 ))
sep='{::}'

if [ "$(uname)" = "Darwin" ]; then
    google_history="$HOME/Library/Application Support/Google/Chrome/Default/History"
    open=open
else
    google_history="$HOME/.config/google-chrome/Default/History"
    open=xdg-open
fi

cp -f "$google_history" /tmp/hist

sqlite3 -separator $sep /tmp/hist \
  "select substr(title, 1, $cols), url from urls order by last_visit_time desc" \
  | awk -F $sep '{printf "%-'$cols's\t\x1b[36m%s\x1b[m\n", $1, $2}' \
  | fzf --ansi --multi \
  | sed 's#.*\(https*://\)#\1#' \
  | xargs $open > /dev/null 2> /dev/null
