#!/usr/bin/env bash

# Open a branch, commit or file in Github.
#
# Requires `opn-cli` to be installed:
#
#   npm install -g opn-cli
#

is_branch_name() {
    git show-ref --verify "refs/heads/$1" >/dev/null 2>&1
}

commitOrFile="$1"
repoUrl="https://github.com/`git repo`"

# No argument, default to current branch.
if [ "$commitOrFile" == "" ]; then
    commitOrFile="`git my-branch`"
fi

# Argument is a branch name, open the branch.
if is_branch_name "$commitOrFile"; then
    opn "$repoUrl/tree/$commitOrFile"
    exit
fi

# Argument is a file, open it in the current commit.
if [ -f "$commitOrFile" ]; then
    opn "$repoUrl/blob/`git sha`/$commitOrFile"
    exit
fi

# Assume argument is a commit ref, resolve it to its hash.
commitOrFile="`git sha $commitOrFile`"

# Open the commit.
opn "$repoUrl/commit/$commitOrFile"
