#!/usr/bin/env bash

# Fixup/amend a commit. This is equivalent to `git commit --amend`
# to modify the last commit, but for any given commit.
#
# Requires fzf (https://github.com/junegunn/fzf) to be installed:
#
#   brew install fzf
#
# Examples:
#
#   git fixup
#   git fixup HASH
#

HASH="$1"

if [[ "$HASH" == "" ]]; then
    # No arguments, select target commit with fzf
    LINE=`git log --pretty=oneline | head -n 100 | fzf` || exit 1
    HASH=`echo "$LINE" | awk '{ print $1 }'`
fi

# Create spacial fixup commit
git commit --fixup="$HASH" --allow-empty

# Run autosquash rebase.
# GIT_SEQUENCE_EDITOR=: avoids opening the rebase sequence.

# TODO: cambiar --preserve-merges por --rebase-merges. Creo que no es un cambio
# automático, me ha dado error al hacer un fixup.
#
# Ver:
# https://stackoverflow.com/questions/7279196/git-how-to-edit-reword-a-merge-commits-message
# https://www.infoq.com/news/2019/07/git-2-22-rebase-merges/

# TODO: meter --preserve-merges también en alias git amend.

GIT_SEQUENCE_EDITOR=: git rebase -i --autosquash --autostash --preserve-merges "$HASH"~1;
