#!/usr/bin/env bash

# Purge file from a repository's history.
# See: https://help.github.com/articles/removing-sensitive-data-from-a-repository/

git filter-branch --force \
    --index-filter "git rm --cached --ignore-unmatch $1" \
    --prune-empty \
    --tag-name-filter cat \
    -- --all
