#!/usr/bin/env bash

# Open a branch, commit or file in Github.
#
# Requires `open-cli` to be installed:
#
#   npm install -g open-cli
#
# Examples:
#
#   git open # opens current branch
#   git open HEAD^
#   git open master
#   git open path/to/my/file.js
#

is_branch_name() {
    git show-ref --verify "refs/heads/$1" >/dev/null 2>&1
}

commitOrFile="$1"
repoUrl="https://github.com/`git repo`"

# No argument, default to current branch.
if [ "$commitOrFile" == "" ]; then
    commitOrFile="`git my-branch`"
fi

# Argument is a branch name, open the branch.
if is_branch_name "$commitOrFile"; then
    open-cli "$repoUrl/tree/$commitOrFile"
    exit
fi

# Argument is a file, open it in the current commit.
if [ -f "$commitOrFile" ]; then
    open-cli "$repoUrl/blob/`git sha`/$commitOrFile"
    exit
fi

# Assume argument is a commit ref, resolve it to its hash.
commitOrFile="`git sha $commitOrFile`"

# Open the commit.
open-cli "$repoUrl/commit/$commitOrFile"
