#!/usr/bin/env bash

# Wrapper of 'git checkout'.
#
# - Uses fzf to select branch if no argument was provided.
#
# - Saves backup of the work tree as a stash before running
#   `git checkout`, in case its deleting data we may want
#   to revert.
#
# Requires fzf (https://github.com/junegunn/fzf) to be installed:
#
#   brew install fzf
#

# No arguments, show available branches to checkout into
if [[ "$#" == "0" ]]; then
    BRANCH=`git recent-branches | fzf` || exit 1
    git checkout "$BRANCH"
    exit $?
fi

# If the work tree is dirty, first create stash as a backup
if [[ `git diff --stat` != '' ]]; then
    git stash push -m "checkout backup (cmd: \"git c $*\")"
    git stash apply > /dev/null
fi

git checkout "$@"
