#!/usr/bin/env bash

# Wrapper of 'git checkout'.
#
# - Uses fzf to select branch if no argument was provided.
#
# - Saves backup of the work tree as a stash before running
#   `git checkout`, in case its deleting data we may want
#   to revert.
#
# Requires fzf (https://github.com/junegunn/fzf) to be installed:
#
#   brew install fzf
#

if [[ "$#" == "0" ]]; then
    BRANCH=`git recent-branches | fzf` || exit 1
    git checkout "$BRANCH"
else
    git stash push --quiet -m "checkout backup (cmd: \"git c $*\"))"
    git stash apply --quiet
    git checkout "$@"
fi
